In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [2]:
url = "https://realpython.github.io/fake-jobs/"
response = requests.get(url)

print(response.status_code)

200

In [3]:
soup = BeautifulSoup(response.text, "html.parser")

In [4]:
job_cards = soup.find_all("div", class_="card-content")

print(len(job_cards))

100

In [5]:
job = job_cards[0]

title = job.find("h2", class_="title").text.strip()
company = job.find("h3", class_="company").text.strip()
location = job.find("p", class_="location").text.strip()
description = job.find("div", class_="content").text.strip()

print(title)
print(company)
print(location)

Senior Python Developer
Payne, Roberts and Davis
Stewartbury, AA

In [6]:
jobs_data = []

for job in job_cards:
    title = job.find("h2", class_="title").text.strip()
    company = job.find("h3", class_="company").text.strip()
    location = job.find("p", class_="location").text.strip()
    description = job.find("div", class_="content").text.strip()
    
    jobs_data.append({
        "Job Title": title,
        "Company": company,
        "Location": location,
        "Description": description
    })

In [9]:
df = pd.DataFrame(jobs_data)
df.head(100)

,Job Title,Company,Location,Description
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA","Stewartbury, AA\n \n\n2021-04-08"
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA","Christopherville, AA\n \n\n2021-04-08"
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA","Port Ericaburgh, AA\n \n\n2021-04-08"
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP","East Seanview, AP\n \n\n2021-04-08"
4,Product manager,Ramirez Inc,"North Jamieview, AP","North Jamieview, AP\n \n\n2021-04-08"
...,...,...,...,...
95,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty","Lake Abigail, AE","Lake Abigail, AE\n \n\n2021-04-08"
96,"Radiographer, diagnostic",Holder LLC,"Jacobshire, AP","Jacobshire, AP\n \n\n2021-04-08"
97,Database administrator,Yates-Ferguson,"Port Susan, AE","Port Susan, AE\n \n\n2021-04-08"
98,Furniture designer,Ortega-Lawrence,"North Tiffany, AA","North Tiffany, AA\n \n\n2021-04-08"
99,Ship broker,"Fuentes, Walls and Castro","Michelleville, AP","Michelleville, AP\n \n\n2021-04-08"

In [10]:
def clean_text(text):
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df["Job Title"] = df["Job Title"].apply(clean_text)
df["Company"] = df["Company"].apply(clean_text)
df["Location"] = df["Location"].apply(clean_text)
df["Description"] = df["Description"].apply(clean_text)

In [11]:
skills = [
    "python", "sql", "excel", "power bi", "tableau",
    "machine learning", "data analysis", "pandas", "numpy"
]

In [12]:
def extract_skills(description):
    description = description.lower()
    found_skills = [skill for skill in skills if skill in description]
    return ", ".join(found_skills)

In [14]:
df["Skills"] = df["Description"].apply(extract_skills)
df.head(20)

,Job Title,Company,Location,Description,Skills
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA","Stewartbury, AA 2021-04-08",
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA","Christopherville, AA 2021-04-08",
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA","Port Ericaburgh, AA 2021-04-08",
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP","East Seanview, AP 2021-04-08",
4,Product manager,Ramirez Inc,"North Jamieview, AP","North Jamieview, AP 2021-04-08",
5,Medical technical officer,Rogers-Yates,"Davidville, AP","Davidville, AP 2021-04-08",
6,Physiological scientist,Kramer-Klein,"South Christopher, AE","South Christopher, AE 2021-04-08",
7,Textile designer,Meyers-Johnson,"Port Jonathan, AE","Port Jonathan, AE 2021-04-08",
8,Television floor manager,Hughes-Williams,"Osbornetown, AE","Osbornetown, AE 2021-04-08",
9,Waste management officer,"Jones, Williams and Villa","Scotttown, AP","Scotttown, AP 2021-04-08",
10,Software Engineer (Python),Garcia PLC,"Ericberg, AE","Ericberg, AE 2021-04-08",
11,Interpreter,Gregory and Sons,"Ramireztown, AE","Ramireztown, AE 2021-04-08",
12,Architect,"Clark, Garcia and Sosa","Figueroaview, AA","Figueroaview, AA 2021-04-08",
13,Meteorologist,Bush PLC,"Kelseystad, AA","Kelseystad, AA 2021-04-08",
14,Audiological scientist,Salazar-Meyers,"Williamsburgh, AE","Williamsburgh, AE 2021-04-08",
15,English as a second language teacher,"Parker, Murphy and Brooks","Mitchellburgh, AE","Mitchellburgh, AE 2021-04-08",
16,Surgeon,Cruz-Brown,"West Jessicabury, AA","West Jessicabury, AA 2021-04-08",
17,Equities trader,Macdonald-Ferguson,"Maloneshire, AE","Maloneshire, AE 2021-04-08",
18,Newspaper journalist,"Williams, Peterson and Rojas","Johnsonton, AA","Johnsonton, AA 2021-04-08",
19,Materials engineer,Smith and Sons,"South Davidtown, AP","South Davidtown, AP 2021-04-08",

In [15]:
df["Job Title"].value_counts().head(10)

Python Programmer (Entry-Level)            3
Legal executive                            2
Manufacturing systems engineer             2
Materials engineer                         2
Futures trader                             2
Software Developer (Python)                2
Back-End Web Developer (Python, Django)    2
Senior Python Developer                    1
Insurance underwriter                      1
Forest/woodland manager                    1
Name: Job Title, dtype: int64

In [16]:
all_skills = df["Skills"].str.split(", ").explode()
all_skills.value_counts().head(10)

    100
Name: Skills, dtype: int64